name: null
title: null
logo: https://www.google.com/imgres?q=madhura%20kulkarni&imgurl=https%3A%2F%2Fcdn.serc.carleton.edu%2Fimages%2FASCN%2Fmadhura_kulkarni_member_corner_200.webp&imgrefurl=https%3A%2F%2Fascnhighered.org%2FASCN%2Fnews%2Fmember_corner.html&docid=uuVsQyOPwXM1WM&tbnid=SokEkYYuVTOcBM&vet=12ahUKEwj828rX0NCVAxU3F1kFHfGyLGAQnPAOegUI1wEQAA..i&w=200&h=150&hcb=2&itg=1&ved=2ahUKEwj828rX0NCVAxU3F1kFHfGyLGAQnPAOegUI1wEQAA
theme: jekyll-theme-minimal
