name: null
title: null
logo: https://www.nku.edu/content/www/academics/artsci/about/centers/cinsam/aboutcinsam/people/_jcr_content/par/columncontrol/column-2/slideshow/image.img.320.medium.jpg/1888651390.jpg
theme: jekyll-theme-minimal
